#!/usr/bin/env bash 

[[ -n $DEBUG ]] && set -x

configs_dir=~/.kube/configs

SELF_CMD="basename ~/.kube/configs/*.yml | sed 's/.yml//'"

list_configs() {
    ls ~/.kube/configs/*.yml
}
set_config() {
    eval export KUBECONFIG=~/.kube/configs/$1.yml

}

choose_config_interactive() {
    local choice
    choice="$(FZF_DEFAULT_COMMAND="${SELF_CMD}" \
    fzf --ansi --no-preview || true)"
    if [[ -z "${choice}" ]]; then
        echo $choice
        echo 2>&1 "error: you did not choose any of the options"
        exit 1
    else
        echo $choice
        set_config "${choice}"
    fi
}

kubeconfig() {
    if [[ $# -eq 0 ]]; then
        if [[ "$(type fzf &>/dev/null; echo $?)" -eq 0 ]]; then
            choose_config_interactive
        else
            list_configs
        fi
    elif [[ "$#" -eq 1 ]]; then
        set_config "${1}"
    else
        usage 
        exit 1
    fi
}

_kube_configs()
{
  local curr_arg;
  curr_arg=${COMP_WORDS[COMP_CWORD]}
  COMPREPLY=( $(compgen -W "- $(basename ~/.kube/configs/*.yml | sed 's/.yml//')" -- $curr_arg ) );
}

complete -F _kube_configs kubeconfig
