require("options")
require("keymaps")
require("plugins.telescope")
require("plugins.oil")
require("plugins.yazi")
-- require("plugins.catppuccin")
require("plugins.nord")
require("plugins.lualine")
require("plugins.which-key")
require("plugins.treesitter")
require("plugins.cmp")
require("plugins.lsp")
require("plugins.typr")
require("plugins.opencode")
require("plugins.snacks")
require("plugins.obsidian")
