require("options")
require("keymaps")
require("plugins.telescope")
require("plugins.oil")
-- require("plugins.catppuccin")
require("plugins.nord")
require("plugins.lualine")
require("plugins.which-key")
require("plugins.treesitter")
require("plugins.obsidian")
require("plugins.render-markdown")
require("plugins.lsp")
